version: '2'
services:
  mesos-master:
    image: seahorse/docker-mesos-master:local
    environment:
      - MESOS_HOSTNAME=mesos-master
      - MESOS_IP=10.254.0.2
      - MESOS_PORT=5050
      - MESOS_QUORUM=1
      - MESOS_ZK=zk://zookeeper:2181/mesos
      - MESOS_LOG_DIR=/var/log/mesos
      - MESOS_REGISTRY=in_memory
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      mesos_net:
        ipv4_address: 10.254.0.2
  mesos-slave1:
    image: seahorse/docker-mesos-slave:local
    privileged: true
    environment:
      - MESOS_HOSTNAME=mesos-slave1
      - MESOS_IP=10.254.0.3
      - MESOS_MASTER=zk://zookeeper:2181/mesos
      - MESOS_LOG_DIR=/var/log/mesos
      - MESOS_LOGGING_LEVEL=INFO
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      mesos_net:
        ipv4_address: 10.254.0.3
  mesos-slave2:
    image: seahorse/docker-mesos-slave:local
    privileged: true
    environment:
      - MESOS_HOSTNAME=mesos-slave2
      - MESOS_IP=10.254.0.4
      - MESOS_MASTER=zk://zookeeper:2181/mesos
      - MESOS_LOG_DIR=/var/log/mesos
      - MESOS_LOGGING_LEVEL=INFO
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      mesos_net:
        ipv4_address: 10.254.0.4
  zookeeper:
    image: seahorse/docker-zookeeper:local
    environment:
      - MYID=1
      - SERVERS=zookeeper
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      mesos_net:
        ipv4_address: 10.254.0.5
networks:
  mesos_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  10.254.0.0/24
          gateway: 10.254.0.1
