version: '2'
services:
  yarn-master:
    image: seahorse/yarn-master:local
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    extra_hosts:
      - "yarn-master:10.254.1.2"
      - "yarn-slave1:10.254.1.3"
      - "yarn-slave2:10.254.1.4"
    networks:
      yarn_net:
        ipv4_address: 10.254.1.2
  yarn-slave1:
    image: seahorse/yarn-slave:local
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    extra_hosts:
      - "yarn-master:10.254.1.2"
      - "yarn-slave1:10.254.1.3"
      - "yarn-slave2:10.254.1.4"
    networks:
      yarn_net:
        ipv4_address: 10.254.1.3
  yarn-slave2:
    image: seahorse/yarn-slave:local
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    extra_hosts:
      - "yarn-master:10.254.1.2"
      - "yarn-slave1:10.254.1.3"
      - "yarn-slave2:10.254.1.4"
    networks:
      yarn_net:
        ipv4_address: 10.254.1.4
networks:
  yarn_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  10.254.1.0/24
          gateway: 10.254.1.1
